version: "3.3"
services:
        webapp:
                build: .
                ports:
                        - "8080:8080"
                depends_on:
                        - db
        db:
                build: ./db
                ports:
                        - "8090:8090"
                volumes:
                        - server-db-data:/data

volumes:
        server-db-data:
