FROM yottadb/yottadb AS yottadb

FROM golang as go

RUN apt update ; apt install libtinfo5
COPY --from=yottadb /opt/yottadb/current /opt/yottadb/current
ENV PKG_CONFIG_PATH=/opt/yottadb/current

WORKDIR /db
ENV GOBIN /db/bin
ENV GOPATH /db/go
ENV PATH=$PATH:/db/db:/db/bin

COPY db ./db
COPY ./schemas ./schemas

RUN . /opt/yottadb/current/ydb_env_set > /dev/null ; go get lang.yottadb.com/go/yottadb
RUN go get -u github.com/a-h/generate/...

WORKDIR /db/db

RUN go generate
RUN go get -v
RUN go install -v

EXPOSE 8090

RUN chmod +x start

CMD ["start"]

